name: Gogstash
on: [push, pull_request, workflow_dispatch]
jobs:
  golangci:
    strategy:
      matrix:
        go-version: [1.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: golangci/golangci-lint-action@v2
      with:
        args: --verbose --timeout=5m

  build:
    strategy:
      matrix:
        go-version: [1.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      CACHE_VERSION: 2021-10-20-0
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
          ~/Library/Caches/go-build
          %LocalAppData%\go-build
        key: ${{ runner.os }}-go-${CACHE_VERSION}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - run: go test -v ./...
    - run: go build
